version = 0.1

[default.deploy.parameters]
stack_name = "aggiedine-backend-service"
resolve_s3 = true
s3_prefix = "aggiedine-backend-service"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
parameter_overrides = "ServiceName=\"aggiedine-backend-service\" Environment=\"development\" LogLevel=\"info\" CognitoUserPoolId=\"us-east-2_zmJwkElq8\" CognitoAppClientId=\"3ej69tpgi4021sg00rhe4t36ma\""
image_repositories = ["HoursScraperFunction=348117807129.dkr.ecr.us-east-2.amazonaws.com/aggiedinebackendservice54e33d2b/hoursscraperfunction5d079786repo"]

[default.global.parameters]
region = "us-east-2"
